### ISSUE TITLE
Rajasthan er no toka chobi

### ISSUE THREAD

**Issue by TathagataChakraborti** [TathagataChakraborti/wheelsacrossindia#10]
Rajasthan er duto na toka chobi lagbe for adventure rajasthan and discover rajasthan banners.

**Comment by muniapal** [comment]
See icon folder in Google drive

**Comment by TathagataChakraborti** [comment]
Google drive e icon folder kothae?!

**Comment by muniapal** [comment]
drive e ache folder ... under images...name: ICON
rs\sampa\Google Drive\WEBSITE_WAI\images for website
i named the picutures Rajasthan 1 Rajasthan 2 in order of appearance on the webpage
