### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by muniapal** [TathagataChakraborti/wheelsacrossindia#2]
need to add photos to each trip as a small gallery

**Comment by TathagataChakraborti** [comment]
Dump all in Dropbox when ready.

**Comment by muniapal** [comment]
teek ache... :-) 
kore debo
pdf files gulo o debo

**Comment by muniapal** [comment]
pdfs have been uploaded....
South india and several ladakh pdf will be done by tomorrow :)
