### ISSUE TITLE
FAQs Background

### ISSUE THREAD

**Issue by muniapal** [TathagataChakraborti/wheelsacrossindia#3]
Contact us and faq er background hlka washout bhabe dile kemon dekhabe?

**Comment by TathagataChakraborti** [comment]
Tahole sob kirom dull hoe jabe kichu color thaka bhalo. Faq er lekhar background ta non transparent kore debo.

**Comment by muniapal** [comment]
teek ache..dekh kemon lage !!!
how goes first day at school?

**Comment by muniapal** [comment]
ar purono website e facebook twitter shob link shoriye dish....
just put the link to my facebook page :-)

**Comment by TathagataChakraborti** [comment]
purono website update kore ki hobe? Eta boshale ota ure jabe.

**Comment by TathagataChakraborti** [comment]
Fixed, thread closed
