### ISSUE TITLE
PDFs missing

### ISSUE THREAD

**Issue by TathagataChakraborti** [TathagataChakraborti/wheelsacrossindia#8]
Trip details er pdf missing

**Comment by TathagataChakraborti** [comment]
AND MAKE SURE PDFS ARE NAMED AS LADAKH1.PDF LADAKH2.PDF IN ORDER OF APPEARANCE IN WEBSITE.

**Comment by muniapal** [comment]
Pdfs have all been updated except for Zanskar Valley Trek and Homestay

**Comment by muniapal** [comment]
Zanskar Valley Trek and Homestay has been created now

**Comment by muniapal** [comment]
where should i put all the updated PDFs ?

**Comment by muniapal** [comment]
I have updated all the PDFs files for Rajasthan, Ladakh, and SOuth INdia in Dropbox . Use these latest ones. If you have uploaded any older versions on the website, then delete those and use these current ones.

**Comment by TathagataChakraborti** [comment]
dropbox ya gdrive?

**Comment by TathagataChakraborti** [comment]
got it.

**Comment by muniapal** [comment]
dropbox
